export const CHAIN_CONFIGS = [
  {
    id: 'monad',
    name: 'Monad',
    color: '#836ef9',
    nativeToken: 'MON',
    coinGeckoId: null as string | null,
    rpcUrl: 'https://testnet-rpc.monad.xyz',
    explorer: 'https://testnet.monadexplorer.com',
    chainId: 10143,
    isEVM: true,
    isTestnet: true,
    description: 'EVM L1',
  },
  {
    id: 'sui',
    name: 'Sui',
    color: '#4da2ff',
    nativeToken: 'SUI',
    coinGeckoId: 'sui' as string | null,
    rpcUrl: 'https://fullnode.mainnet.sui.io:443',
    explorer: 'https://suiscan.xyz',
    isEVM: false,
    isTestnet: false,
    description: 'Move L1',
  },
  {
    id: 'aptos',
    name: 'Aptos',
    color: '#00d4aa',
    nativeToken: 'APT',
    coinGeckoId: 'aptos' as string | null,
    rpcUrl: 'https://fullnode.mainnet.aptoslabs.com/v1',
    explorer: 'https://explorer.aptoslabs.com',
    isEVM: false,
    isTestnet: false,
    description: 'Move L1',
  },
  {
    id: 'solana',
    name: 'Solana',
    color: '#9945ff',
    nativeToken: 'SOL',
    coinGeckoId: 'solana' as string | null,
    rpcUrl: 'https://api.mainnet-beta.solana.com',
    explorer: 'https://explorer.solana.com',
    isEVM: false,
    isTestnet: false,
    description: 'High-perf L1',
  },
  {
    id: 'arc',
    name: 'Arc',
    color: '#ff6b6b',
    nativeToken: 'ARC',
    coinGeckoId: null as string | null,
    rpcUrl: '',
    explorer: '',
    isEVM: true,
    isTestnet: true,
    description: 'EVM Protocol',
  },
] as const
